#! /bin/bash
ROOT=`cd $(dirname $0); pwd`
CONFDIR=$ROOT/config

# 定义erlang vm选项
ERL=erl
POLL=true
ASYNC=8
SMP=true
ERL_PROCESSES=500000
CONNECT_ALL=true
DATETIME=`date "+%Y%m%d-%H%M%S"`
export ERL_CRASH_DUMP=$ROOT/erl_crash_$DATETIME.dump
export ERL_MAX_PORTS=102400
export ERL_MAX_ETS_TABLES=10000
export HOME=$ROOT
GAME_CONF_FILE=$CONFDIR/game.config

# 运行的程序及控制文件
APP_MOD=main
APP_CTL=game_ctl
# define additional environment variables
EBINS="$ROOT/ebin"

STATUS_SUCCESS=0    # 成功
STATUS_NORUN=1      # 未运行
STATUS_USAGE=2      # 使用错误
STATUS_BADRPC=3     # rpc调用错误
STATUS_ERROR=4      # 其它错误
STATUS_STARTING=5   # 正在开服中
STATUS_RUNNING=6    # 运行中
STATUS_STOPING=7    # 正在关服中

# 重新加载的系统数据
RELOAD_TYPE=code

# 打印错误
error() {
    echo -e "[1;41m[错误][`date +"%F %T"`][0m ${SERVER_ID}服[${ERLANG_NODE}]$1"
    exit 1
}

# 打印信息
echo2() {
    echo -e "[1;42m[操作][`date +"%F %T"`][0m ${SERVER_ID}服[${ERLANG_NODE}]$1"
}

# 打印信息(不换行)
echo2_n() {
    echo -n -e "[1;42m[操作][`date +"%F %T"`][0m ${SERVER_ID}服[${ERLANG_NODE}]$1"
}

# 打印警告
warn() {
    echo -e "[1;43m[警告][`date +"%F %T"`][0m ${SERVER_ID}服[${ERLANG_NODE}]$1"
}

# 获取内网ip
getip() {
    echo `LANG=en_US; ifconfig | grep 'inet addr:' | grep -v '127.0.0.1' | cut -d: -f 2 | awk '{print $1}'`
}

# 使用说明
usage ()
{
    echo ""
    echo "用法:"
    echo "$0 ACTION [OPTION]"
    echo "ACTION:"
    echo "  live            交互方式启动"
    echo "  start           后台方式启动"
    echo "  async_start     后台方式启动(异步)" 
    echo "  status          获取后台运行状态"
    echo "  attach          通过Erlang shell连接后台运行节点"
    echo "  stop            立即停止节点(同步)"
    echo "  reload          重新加载数据或代码"
    echo "  count           获取在线人数"
    echo "  version         获取版本信息"
    echo "  switch_db       切换游戏服数据"
    echo "  check_db        检查游戏服数据状态"
    echo ""
    echo "OPTION:"
    echo "  -h, --help              显示本信息"
    echo "  -s, --smp=true          是否使用smp(true|false,默认为true)"
    echo "  -c, --cookie=Cookie     节点cookie(默认\"\")"
    echo "  -f, --conf=Conf         指明使用的配置文件(默认game.conf)"
    echo "  -r, --reload=Type       指明要reload的系统数据:code,config或者指定模块名称"
    echo "  -n, --name=Name         指明要管理的服务器名称"
    echo ""
}

# 修改ulimit
change_ulimit() {
    if ! ulimit -HSn 102400 2> /dev/null ; then
        ## error "请确保具有root权限"
        echo "请确保具有root权限"
    fi
}

# 查询运行中节点的信息
rpc() 
{
    $ERL \
      $NAME_FLAG ${CTL_NAME}_ctl@$HOST \
      -noinput \
      -pa $EBINS $DEPS_EBIN_DIR\
      -setcookie ${COOKIE} \
      -s ${APP_CTL} -extra $ERLANG_NODE $@
}

# 打印rpc返回信息
print_rpc_return ()
{
    case $1 in
    $STATUS_SUCCESS) 
        echo ""
        ;;
    $STATUS_NORUN) 
        warn "未运行!"
        ;;
    $STATUS_USAGE) 
        error "命令不支持! $0 -h查看帮助"
        ;;
    $STATUS_BADRPC) 
        error "RPC发生错误"
        ;;
    $STATUS_ERROR) 
        error "请求发生错误"
        ;;
    $STATUS_STARTING) 
        echo2 "正在开服中"
        ;;
    $STATUS_RUNNING) 
        echo2 "运行中"
        ;;
    $STATUS_STOPING) 
        echo2 "正在停服中"
        ;;
    *)
        error "未知命令! $0 -h查看帮助"
    esac
    exit $1
}


# 判断节点是否运行
is_started () 
{
    rpc status
    result=$?
    if [  "$result" = "$STATUS_RUNNING" ]; then
        return 0
    fi
    return $result
}


# 判断节点是否crash
is_crashed() 
{
    if [ -f ${ERL_CRASH_DUMP} ]; then
        return 0
    fi
    return 1
}


# start interactive server
live ()
{
    change_ulimit
    $ERL \
      $NAME_FLAG $ERLANG_NODE \
      -pa $EBINS $DEPS_EBIN_DIR \
      -setcookie ${COOKIE} \
      -s ${APP_MOD} start \
      $ERLANG_OPTS --extra $ARGS "$@"
}


# 启动server
start ()
{
    change_ulimit
    ensure_log_dir
    if is_started; then
        warn "节点$ERLANG_NODE已经启动"
        exit 0
    fi
    echo2_n "开始启动" 
    # 等待1秒钟
    sleep 1
    $ERL \
      $NAME_FLAG $ERLANG_NODE \
      -noinput -detached \
      -hidden \
      -pa $EBINS $DEPS_EBIN_DIR\
      -setcookie ${COOKIE} \
      -kernel error_logger silent \
      -sasl sasl_error_logger \{file,\"$SASL_LOG\"\} \
      -kernel inet_dist_listen_min 10000 inet_dist_listen_max 20000 \
      -s ${APP_MOD} start\
      $ERLANG_OPTS $ARGS "$@"
    
    if [ "$1" = "async" ]; then
        echo ""
        echo2 "启动中，请稍候通过$0 status检测"
        exit 0
    fi

    RETRY=0
    while true; do
        if [ $? -ne 0 ]; then
            echo ""
            error "启动失败:$?"
        else
            if is_started; then
                break
            fi
            if is_crashed; then
                echo ""
                error "启动失败,发生crash!"
            else
                let RETRY++
                echo -n "."
                sleep 1
            fi
        fi
    done
    echo ""
    echo2 "启动成功"
}

# 获取状态
status ()
{
    if is_started; then
        echo2 "运行中"
    else
        print_rpc_return $?
    fi  
}

# 连接到节点内
attach ()
{
    if ! is_started; then
        error "${SERVER_ID}服[$ERLANG_NODE]未启动"
    fi
    $ERL \
      $NAME_FLAG ${NAME}_attach@$HOST \
      -setcookie ${COOKIE} \
      -remsh $ERLANG_NODE \
      $ERLANG_OPTS $ARGS "$@"
}

# 停止节点
stop ()
{
    PID=`ps aux | grep "name $ERLANG_NODE" | grep -v "grep" | awk '{print $2}'`
    if [ "$PID" != '' ] ; then
        if rpc stop $@; then
            echo2_n "正在关服."
        else
            print_rpc_return $?
        fi  
        RETRY=0
        while true; do
            sleep 1
            PID=`ps aux | grep "name $ERLANG_NODE" | grep -v "grep" | awk '{print $2}'`
            if [ $RETRY -ge 60 ]; then
                echo ""
                echo2 "关服失败，强制关闭进程"
                ARRAY=($PID)
                for data in ${ARRAY[@]}
                do
                    kill -9 ${data}
                done
                return 0
            else
                let RETRY++
                if [ "$PID" != '' ]; then
                    echo -n "."
                else
                    echo ""
                    echo2 "关服成功"
                    return 0
                fi
            fi
        done
    else 
        echo2 "已停止"
    fi
}

# 重新加载
reload ()
{
    echo ${RELOAD_TYPE}
    if rpc reload ${RELOAD_TYPE}; then
        echo2 "重新加载${RELOAD_TYPE}成功"
    else
        error "重新加载${RELOAD_TYPE}失败"
    fi  
}

# 获取在线人数
count ()
{
    if ! is_started; then
        echo 0
        exit 0
    fi
    rpc count
}


# 获取版本信息
version ()
{
    if ! is_started; then
        echo 0
        exit 0
    fi
    rpc version
}

# 切换数库
switch_db ()
{
    if ! is_started; then
        echo 0
        exit 0
    fi
    if rpc switch_db;then
        echo2 "切换数据库成功"
    else
        error "切换数据失败"
    fi
}

# 数据库状态
check_db ()
{
    if ! is_started; then
        echo 0
        exit 0
    fi
    if rpc check_db;then
        echo2 "数据库连接成功"
    else
        error "数据连接失败"
    fi
}


# sasl的路径
ERRLOGDIR=$ROOT/logs
ensure_log_dir()
{
    if [ ! -d $ERRLOGDIR ]; then
        mkdir -p $ERRLOGDIR || (echo "make $ERRLOGDIR error!"; exit 1)
    fi
    SASL_LOG=$ERRLOGDIR/game_${SERVER_ID}_${DATETIME}.sasl
}


# parse command line parameters
while [ $# -ne 0 ] ; do
    PARAM=$1
    shift
    case $PARAM in
        --) break ;;
        --cookie|-c) COOKIE=$1 ; shift ;;
        --conf|-f) 
            GAME_CONF_FILE=$1;
            export GAME_CONF_FILE=${GAME_CONF_FILE}; 
            shift ;;
        --help|-h) usage; exit 0;;
        --smp|-s) SMP=$1; shift;;
        --reload|-r) RELOAD_TYPE=$@; break;;
        *) ARGS="$ARGS $PARAM" ;;
    esac
done

# 获取server_id
SERVER_TYPE=`cat ${GAME_CONF_FILE}  | grep -ri '{server_type,' | sed -e 's/{server_type,\s*\(.*\)}.*/\1/'`
SERVER_ID=`cat ${GAME_CONF_FILE}  | grep -ri '{server_id,' | sed -e 's/{server_id,\s*\(.*\)}.*/\1/'`
PLATFORM_ID=`cat ${GAME_CONF_FILE}  | grep -ri '{platform,' | sed -e 's/{platform,\s*\"\(.*\)\"}.*/\1/'`
SERVER_PREFIX=`cat ${GAME_CONF_FILE}  | grep -ri '{prefix,' | sed -e 's/{prefix,\s*\(.*\)}.*/\1/'`
SERVER_IP=`cat ${GAME_CONF_FILE} | grep -ri '{server_ip,' | sed -e 's/{server_ip,\s*\"\(.*\)\"}.*/\1/'`
#SERVER_IP=`ifconfig eth1 | grep "inet addr" | awk '{print $2}' | awk -F: '{print $2}'`
SERVER_PORT=`cat ${GAME_CONF_FILE} | grep -ri '{server_port,' | sed -e 's/{server_port,\s*\(.*\)}.*/\1/'`

if [ "$SERVER_PREFIX" = "" ]; then
    SERVER_PREFIX="s"
fi
SERVER_ID=${PLATFORM_ID}_${SERVER_PREFIX}${SERVER_ID}_${SERVER_PORT}

# 节点名
ERLANG_NODE=${SERVER_TYPE}_${SERVER_ID}@${SERVER_IP}
COOKIE="node-cookie"

NAME=${ERLANG_NODE%%@*}
HOST=${ERLANG_NODE##*@}
TIMESTAMP=`date "+%Y%m%d-%H%M%S_%N"`
CTL_NAME=${NAME}"_"${TIMESTAMP}
NAME_FLAG=-name

LOCAL_IP=$(getip)
#if [ "$NAME_FLAG" = "-name" -a "$HOST" !=  "$LOCAL_IP" ]; then 
#    error "节点名称:$ERLANG_NODE与本机ip:$LOCAL_IP不相符"
#fi

if [ "$SMP" = "false" ]; then
    SMP=disable
else
    SMP=enable
fi

ERLANG_OPTS="-connect_all $CONNECT_ALL +K $POLL -smp $SMP +P $ERL_PROCESSES \
    +t 10485760 +fnu +hms 8192 +hmbs 8192 +zdbbl 81920 -v"

DEPS_DIR=${ROOT}/deps
DEPS_EBIN_DIR=`find $DEPS_DIR -name ebin -type d`
#DEPS_EBIN_DIR="-pa $ROOT/deps/protobuffs/ebin \
#              -pa $ROOT/deps/meck/ebin"


case $ARGS in
    '') usage;;
    ' live') live;;
    ' start') start sync;;
    ' async_start') start async;;
    ' status') status;;
    ' attach') attach;;
    ' stop') stop 0;;
    ' count') count;;
    ' reload') reload;;
    ' version') version;;
    ' switch_db') switch_db;;
    ' check_db') check_db;;
    *) usage; exit 1;;
esac

