{
	[
		'src/*',		
		'src/*/*',		
		'src/*/*/*',
		'check_data/*',
		'ex_code/proto/*'
	]
	,[
		{i, "include/"},
		{i, "ex_code/proto/"},
		{outdir, "ebin"},
		inline,
		warnings_as_errors
	]
}.
{
	[
		'ex_code/data/cn/*'
	]
	,[
		{i, "include/"},
		{outdir, "deps/data_cn"},
		inline,
		warnings_as_errors
	]
}.
