{
	[   
	'src/*',    
	'src/*/*',    
	'src/*/*/*',
	'src/*/*/*/*'
	]   
	,[  
	{i, "include/"},
	{i, "include/inst/"},
	{i, "include/deps/"},
	{i, "src/deps/protobuffs/include"},
	{outdir, "ebin"},
	inline
	]   
}.

